version: "3.8"
services:
    web:
        image: nginx:1.19.2-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./secure.conf:/etc/nginx/conf.d/secure.conf
            - ./ssl.crt:/var/www/ssl.crt:ro
            - ./ssl.key:/var/www/ssl.key:ro
            - ./ssl.pem:/var/www/ssl.pem:ro
        links:
            - php
    php:
        build:
            context: images/php
        volumes:
            - ./src:/var/www/html
        links:
            - db
        env_file:
          - app.env
    db:
        build:
            context: images/postgres
        environment:
            - POSTGRES_DB=mydatabase
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
        volumes:
            - ./data/database:/var/lib/postgresql/data
    adminer:
        image: adminer:4.7.7-standalone
        restart: always
        links:
            - db
        ports:
            - 5000:8080